name: PHP Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phplint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@2.5
        with:
          testMode: true
          verboseMode: true
          configPath: "pint.json"
